# Generated by Django 6.0.5 on 2026-06-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='btn',
            field=models.CharField(default='Explore Our Menu', max_length=50),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicesection',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='specialheader',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='specialitem',
            name='btn',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='specialitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
