# Generated by Django 6.0.5 on 2026-06-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_herosection_btn_alter_herosection_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_section',
        ),
        migrations.RemoveField(
            model_name='specialitem',
            name='special_section',
        ),
    ]
