# Generated by Django 6.0.5 on 2026-06-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_services_service_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialitem',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
