# Generated by Django 6.0.5 on 2026-06-13 05:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_customerfeedback_favitem_favoriteheader_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedback',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
